version: "3.8"

services:
  next:
    image: "protofy/workspace"
    entrypoint: "sh -c 'cd apps/next && yarn prepare-dev && yarn dev-standalone'"
    ports:
      - 3000:3000
    environment:
      - PROXY_API_URL=http://core:8000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ../../:/workspace
      - protofy_modules:/workspace/node_modules
      - protofy_next:/workspace/apps/next/.next
      
volumes:
  protofy_modules:
    external: true
  protofy_next:
    external: true
