version: '3.8'

services:
  core:
    build:
      context: ../..  # This should be set to two levels up from where the Dockerfile is, if that's where the folders you want to copy are located.
      dockerfile: apps/core/Dockerfile
    entrypoint: "yarn prod-standalone"
    ports:
      - 8080:8080
    environment:
      - MQTT_URL=mqtt://localhost:1883
      - PROXY_API_URL=http://core:8080
      - ADMIN_API_URL=http://core:3002
      - API_URL=http://api:4001
      - SITE_URL=http://next:4000 
      - ADMIN_SITE_URL=http://admin:4003 
      - DOCS_SITE_URL=http://nextra-compiled:7700
      - NODE_ENV=production