version: '3.8'

services:
  api:
    build:
      context: ../..  # This should be set to two levels up from where the Dockerfile is, if that's where the folders you want to copy are located.
      dockerfile: apps/api/Dockerfile  # Adjust the path to where your Dockerfile is located relative to the context.
    entrypoint: "yarn prod-standalone"
    environment:
      - MQTT_URL=mqtt://core:1883
      - PROXY_API_URL=http://core:8080
      - NODE_ENV=production